// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUD_Project.Models;

public partial class Department
{
    public int DeptId { get; set; }

    public string Dept_Name { get; set; }

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}