// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUD_Project.Models;

public partial class Student
{
    public int St_Id { get; set; }

    public string St_FName { get; set; }

    public string St_LName { get; set; }

    public int? St_Age { get; set; }

    public string St_Address { get; set; }

    public int? St_DeptId { get; set; }

    public virtual Department St_Dept { get; set; }
}